name: Build and Deploy docker image in ECS with GitHub action

on:
  push:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    environment: dev
     
    env:
      LOG_FILE: build-report.log
      MAIL_RECIPIENTS: ${{ vars.MAIL_RECIPIENTS }}
      BRANCH_NAME: ${{ github.ref_name }}
      DOCKER_ENV: ${{ vars.DOCKER_ENV }}
      AWS_ENV: ${{ vars.AWS_ENV }}
      GIT_PROJECT_SLUG: ${{ vars.GIT_PROJECT_SLUG }}
      GIT_TEAM_NAME: ${{ vars.GIT_TEAM_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
    
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        continue-on-error: true
        with:
          working-directory: ./terraform
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Run Checkov IaC scanner
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: ./terraform
          framework: terraform

  build-and-deploy:
    needs: [security-scan]
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref_name == 'deel_ip_test' || github.ref_name == 'main'
    
    steps:
    - uses: actions/checkout@v4

    - name: Debug secrets
      run: |
        echo "Branch: ${{ github.ref_name }}"
        echo "AWS_ACCESS_KEY_ID set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
        echo "AWS_SECRET_ACCESS_KEY set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Test AWS credentials
      run: aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.1

    - name: Terraform Init
      working-directory: ./terraform
      timeout-minutes: 5
      run: terraform init

    # - name: Force unlock state
    #   working-directory: ./terraform
    #   continue-on-error: true
    #   run: |
    #     terraform force-unlock -force abef8197-e4f8-225a-f682-707a40fdb14d


    - name: Terraform Plan (ECR and Infra)
      working-directory: ./terraform
      run: terraform plan -var-file="envVars/dev/dev.tfvars" 2>&1 | tee terraform-plan-infra.log

    - name: Upload Terraform Plan Log (Infra)
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-infra-log
        path: ./terraform/terraform-plan-infra.log

    - name: Terraform Apply (ECR and Infra)
      working-directory: ./terraform
      run: terraform apply -var-file="envVars/dev/dev.tfvars" -auto-approve 2>&1 

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        aws-region: eu-west-2

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Upload Terraform Plan Log
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-log  
        path: ./terraform/plan.log
    
    - name: Terraform Apply
      working-directory: ./terraform
      env:
        TF_VAR_image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      run: terraform apply -var-file="envVars/dev/dev.tfvars" -auto-approve 2>&1 | tee terraform-apply.log

    - name: Upload Terraform Apply Log
      uses: actions/upload-artifact@v4
      with:
        name: terraform-apply-log
        path: ./terraform/terraform-apply.log

    - name: Wait for deployment
      run: |
       sleep 60
       echo "Waiting for deployment to complete..."
    # or the below and this is proper way to do it
    # - name: Wait for ECS service and ALB target to be healthy
    #   run: |
    #     SERVICE_NAME="deel-test-app"
    #     CLUSTER_NAME="deel-test-app-cluster"
    #     TG_ARN=$(aws elbv2 describe-target-groups --names deel-test-app-tg --query 'TargetGroups[0].TargetGroupArn' --output text)
    #     TIMEOUT=600
    #     INTERVAL=15
    #     ELAPSED=0

    #     echo "Waiting for ECS service to be stable..."
    #     while [[ $ELAPSED -lt $TIMEOUT ]]; do
    #       STATUS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].deployments[0].rolloutState' --output text)
    #       if [[ "$STATUS" == "COMPLETED" ]]; then
    #         echo "ECS service is stable."
    #         break
    #       fi
    #       sleep $INTERVAL
    #       ELAPSED=$((ELAPSED + INTERVAL))
    #     done

    #     echo "Waiting for ALB target to be healthy..."
    #     ELAPSED=0
    #     while [[ $ELAPSED -lt $TIMEOUT ]]; do
    #       HEALTH=$(aws elbv2 describe-target-health --target-group-arn $TG_ARN --query 'TargetHealthDescriptions[0].TargetHealth.State' --output text)
    #       if [[ "$HEALTH" == "healthy" ]]; then
    #         echo "ALB target is healthy."
    #         break
    #       fi
    #       sleep $INTERVAL
    #       ELAPSED=$((ELAPSED + INTERVAL))
    #     done 

    
    - name: Get ALB DNS name
      id: get-alb-dns
      run: |
        ALB_DNS=$(aws elbv2 describe-load-balancers --names deel-test-app-alb --query 'LoadBalancers[0].DNSName' --output text)
        echo "alb_dns=$ALB_DNS" >> $GITHUB_OUTPUT
        echo "Application URL: http://$ALB_DNS"

    - name: DAST Security Scan with OWASP ZAP
      uses: zaproxy/action-baseline@v0.12.0
      continue-on-error: true
      with:
        target: 'http://${{ steps.get-alb-dns.outputs.alb_dns }}'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
        fail_action: false

    - name: Upload DAST Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dast-report
        path: report_html.html


    # can be added later

    - name: Get commit message
      if: always()
      id: get_commit_message
      run: |
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")
        echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "Commit message: $COMMIT_MSG" 

    # - name: Send a notification email with the build result
    #   if: always()  # Ensures the email is sent on both success and failure  
    #   uses: reusable-workflows/send-email@v1
    #   env:
    #       SEND_EMAIL_subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    #       SEND_EMAIL_body: |
    #         ${{ github.workflow }} pipeline ${{ github.job }} job has a ${{ job.status }} status.
    #         Branch: ${{ github.ref }}
    #         Commit: ${{ github.sha }}
    #         Commit Message: ${{ steps.get_commit_message.outputs.message }}
    #         If you want to view run details:
    #         ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    #       SEND_EMAIL_recipients: ${{ vars.MAIL_RECIPIENTS }}
    #       GITH_COM_TOKEN: ${{ secrets.MY_GIT_HUB_COM_TOKEN }}
    #       SEND_EMAIL_attachments: ${{ env.LOG_FILE }}	