name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: deel-test-app

jobs:
  tfsec-scan: # Additional Hardening: TFSec IaC Security Scanner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run TFSec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working-directory: ./terraform

  snyk-scan: # Additional Hardening: Snyk Dependency and Container Scanner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Snyk Scan
      uses: snyk/actions@master
      with:
        command: test
  security-scan: # Security Hardening: Vulnerability and Secrets Scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  iac-security: # Security Hardening: IaC Misconfiguration Scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkov IaC scanner
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./terraform
        framework: terraform
        output_format: sarif
        output_file_path: checkov-results.sarif
    - name: Upload Checkov scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: checkov-results.sarif

  build-and-deploy:
    needs: [security-scan, iac-security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
        # --- Security Hardening: Vulnerability and Secrets Scanning ---
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # --- Security Hardening: IaC Misconfiguration Scanning ---
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./terraform
      env:
        TF_VAR_image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      run: terraform plan
    
    - name: Terraform Apply
      working-directory: ./terraform
      env:
        TF_VAR_image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      run: terraform apply -auto-approve