name: Build and Deploy docker image in ECS with GitHub action

on:
  push:
  # the branch is set to deel_ip_test in git env var for testing purpose.

env:
  LOG_FILE: build-report.log
  MAIL_RECIPIENTS: ${{ vars.MAIL_RECIPIENTS }}
  BRANCH_NAME: ${{ github.ref_name }}
  DOCKER_ENV: ${{ vars.DOCKER_ENV }}
  AWS_ENV: ${{ vars.AWS_ENV }}
  GIT_PROJECT_SLUG: ${{ vars.GIT_PROJECT_SLUG }}
  GIT_TEAM_NAME: ${{ vars.GIT_TEAM_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  DEPLOY_BRANCH: deel_ip_test


jobs:
  tfsec-scan: # Additional Hardening: TFSec IaC Security Scanner
    runs-on: ubuntu-latest
   # environment: dev
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Run TFSec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working-directory: ./terraform


  security-scan: # Security Hardening: Vulnerability and Secrets Scanning
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'

  iac-security: # Security Hardening: IaC Misconfiguration Scanning
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkov IaC scanner
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./terraform
        framework: terraform

  build-and-deploy:
    needs: [security-scan, iac-security]
    runs-on: ubuntu-latest
    if: github.ref_name == 'deel_ip_test' || github.ref_name == 'main'
    
    steps:
    - uses: actions/checkout@v4
    
        # --- Security Hardening: Vulnerability and Secrets Scanning ---
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #aws-region: ${{ vars.AWS_REGION }}
        aws-region: eu-west-2
        

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        aws-region: eu-west-2
    
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # --- Security Hardening: IaC Misconfiguration Scanning ---
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./terraform
      env:
        TF_VAR_image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      run: terraform plan
    
    - name: Terraform Apply
      working-directory: ./terraform
      env:
        TF_VAR_image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      run: terraform apply -auto-approve