name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./terraform
        timeout-minutes: 5
        run: terraform init -backend-config="envVars/dev/backend.tf" -lock=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -generate-config-out=generated.tf -var-file="envVars/dev/dev.tfvars" 2>&1

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -var-file="envVars/dev/dev.tfvars" -auto-approve 2>&1

      - name: Terraform Destroy 
        working-directory: ./terraform
        run: terraform destroy -var-file="envVars/dev/dev.tfvars" -auto-approve 2>&1 | tee terraform-destroy.log

      - name: Upload Destroy Log
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-log
          path: ./terraform/terraform-destroy.log
